print()
print()
best_film = input ("What is your favorit3 film? ")
launch_year = input ("What y3ar was it r3l3as3d? ")
print()
print()
print (best_film + " was r3l3as3d in " + launch_year +".")
print()
print()